version: "3"

volumes:
    investments-db:
        driver: local

services:
    db:
        image: postgres:15.4-alpine
        volumes:
            - investments-db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: investments
            POSTGRES_USER: investments
            POSTGRES_PASSWORD: test1234
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        ports:
            - "${POSTGRES_PORT:-5432}:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U investments"]
            interval: 5s
            timeout: 5s
            retries: 5
